// Generated by temple-t. Runs the project's post-tool command after
// file-mutating tools (OMP equivalent of Claude Code's Write|Edit|MultiEdit).
const FILE_MUTATING_TOOLS = new Set(["write", "edit", "ast_edit", "apply_patch"]);
const COMMAND = "swift format format --in-place --recursive wasmbox wasmboxPackage/Sources wasmboxPackage/Tests wasmboxPackage/Package.swift wasmboxUITests";

export default function (pi) {
  pi.on("tool_result", async (event, ctx) => {
    if (event.isError || !FILE_MUTATING_TOOLS.has(event.toolName)) return;
    if (event.toolName === "ast_edit" && event.details?.applied !== true) return;
    const path = typeof event.input?.path === "string"
      ? event.input.path.toLowerCase()
      : "";
    if (
      event.toolName === "write" &&
      path.startsWith("xd://") &&
      path !== "xd://resolve" &&
      !path.startsWith("xd://resolve:")
    ) return;
    try {
      const result = await pi.exec("sh", ["-c", COMMAND], { cwd: ctx.cwd });
      if (result.code !== 0) {
        pi.logger.error(`post-tool hook failed with exit code ${result.code}: ${result.stderr || result.stdout}`);
      }
    } catch (error) {
      pi.logger.error(`post-tool hook failed: ${error}`);
    }
  });
}
